name: API docs

on:
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}-${{ github.event_path }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Requirements
      run: |
        brew install doxygen
    - name: Remove stale Git lock files
      run: |
        find .git -name '*.lock' -type f -delete || true
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Build docs
      run: make docs
        && cd docs/_build/html
        && touch .nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/_build/html # The folder the action should deploy.
